# Generated by Django 4.1.3 on 2022-11-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_post', '0002_alter_react_reacted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commented_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='posted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='react',
            name='reacted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
