# Generated by Django 4.1.3 on 2022-11-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_post', '0003_alter_comment_commented_at_alter_post_posted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='react',
            name='reacted_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
